name: Build AiTag App

on:
  push:
    tags:
      - '*'
        
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get latest DeepDanbooru
        run: |
          git clone https://github.com/KichangKim/DeepDanbooru Source
          Copy-Item ./Source/deepdanbooru . -Recurse -Force
          Remove-Item ./Source -Force -Recurse
        shell: powershell

      - name: Prepare DeepDanbooru model
        run: |
          $zipUrl = "https://github.com/KichangKim/DeepDanbooru/releases/download/v3-20211112-sgd-e28/deepdanbooru-v3-20211112-sgd-e28.zip"
          $zipPath = "$Pwd\deepdanbooru.zip"
          $extractPath = "$Pwd\model"
          $retryCount = 3
          $retryDelay = 10
          $retry = 0
          do {
            Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
            if (-not (Test-Path $zipPath) -or (Get-Item $zipPath).Length -ne 598286910) {
              Write-Error (Get-Item $zipPath).Length
              Write-Error "Can't load model"
              $retry++
              Start-Sleep -Seconds $retryDelay
            } else {
              $retry = $retryCount
            }
          } while ($retry -lt $retryCount)
          if ($retry -eq $retryCount) {
            Write-Host "Model downloaded successfully"
          } else {
            Write-Error "Failed to download model after $retryCount attempts"
            exit 1
          }
          if (-not (Test-Path $extractPath)) { New-Item -Path $extractPath -ItemType Directory }
          Expand-Archive -Path $zipPath -DestinationPath $extractPath -Force
          Remove-Item $zipPath -Force
        shell: powershell

      - name: Cache model, deepdanboru
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.0.0
        with:
          path: |
            model
            deepdanbooru
          key: ${{ runner.os }}

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@a41619580c25efb59dfc062e92990914141abcad # v0.10.2
        with:
          versionSpec: '5.5.0'

      - uses: actions/setup-dotnet@3447fd6a9f9e57506b15f895c5b76d3b197dc7c2 # v3.2.0
        with:
          dotnet-version: '3.1.x'

      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0

      - name: Run GitVersion
        id:   gitversion
        uses: GitTools/actions/gitversion/execute@a41619580c25efb59dfc062e92990914141abcad # v0.10.2
  
      - name: Install Python
        run: choco install python --version=3.10.11

      - name: Set up Python environment
        run: |
          python -m venv .venv
          .\.venv\Scripts\activate
          pip install --upgrade pips
          pip install -r requirements.txt

      - name: Cache .venv
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.0.0
        with:
          path: |
            .venv
          key: ${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      - name: Build the application
        run: |
          .\.venv\Scripts\activate
          pyinstaller --onedir --add-data "model;model" aitag.py
        shell: powershell

      - name: Test run of the built application
        run: |
          .\dist\aitag\aitag.exe --dry-run
        shell: powershell

      - name: Package built application
        run: |
          Compress-Archive -Path .\dist\aitag\* -DestinationPath aitag_app_v${{ steps.gitversion.outputs.majorMinorPatch }}.zip
        shell: powershell

      - name: Upload app to github release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1.0.0
        with:
          files: ./aitag_app_v*.*
          body_path: ./RELEASE.md
          name: AiTag ${{ steps.gitversion.outputs.majorMinorPatch }}
